# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07da45df102c3ee4aae8339c14a26289b9d1c6ffe240066e8c3ccadce192de97220a67ca050270e6776cceb9587d9a6831f2cd0f226781c332610d47a0b2c157

test:
  secret_key_base: d0767d7cc32019a3b8d28dcda87f1eee1e7abf763985f8000b0e77b29d785c4b51a61fd22cbbe842b7695189d8988865a2b4470e42ffe959eb4e83208438404c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
